services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo_staging
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: http://localhost:5001
    ports:
      - "3001:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongo-staging:/data/db

volumes:
  mongo-staging: