# Use official Node image
FROM node:24-alpine

# Set environment
ENV NODE_ENV=production

# Set working directory inside container
WORKDIR /app

# Copy package files first
COPY package*.json ./

# Install production dependencies only
RUN npm ci --omit=dev

# install curl
RUN apk add --no-cache curl

# Copy all files
COPY . .

# Expose port
EXPOSE 5000

# Start app
CMD ["npm", "start"]
